// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Gemini",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Gemini",
            targets: ["AppModule"],
            bundleIdentifier: "com.timi2506.Gemini",
            teamIdentifier: "P6PV2R9443",
            displayVersion: "1.4.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .incomingNetworkConnections(),
                .outgoingNetworkConnections()
            ],
            appCategory: .productivity
        )
    ],
    dependencies: [
        .package(url: "https://github.com/google-gemini/generative-ai-swift", "0.5.6"..<"1.0.0"),
        .package(url: "https://github.com/tomdai/markdown-webview.git", "2.0.1"..<"3.0.0"),
        .package(url: "https://github.com/evgenyneu/keychain-swift.git", "24.0.0"..<"25.0.0"),
        .package(url: "https://github.com/ZeeZide/CodeEditor.git", "1.2.6"..<"2.0.0"),
        .package(url: "https://github.com/timi2506/AsyncButton.git", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "GoogleGenerativeAI", package: "generative-ai-swift"),
                .product(name: "MarkdownWebView", package: "markdown-webview"),
                .product(name: "KeychainSwift", package: "keychain-swift"),
                .product(name: "CodeEditor", package: "CodeEditor"),
                .product(name: "AsyncButton", package: "AsyncButton")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)